FROM alpine:3.23@sha256:fd791d74b68913cbb027c6546007b3f0d3bc45125f797758156952bc2d6daf40

RUN apk add --no-cache ca-certificates tzdata

ARG TARGETPLATFORM
COPY $TARGETPLATFORM/catacomb /usr/bin/catacomb

RUN adduser -D -u 65532 catacomb
USER catacomb

ENTRYPOINT ["/usr/bin/catacomb"]
CMD ["--help"]
