FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

RUN apk add --no-cache ca-certificates tzdata

ARG TARGETPLATFORM
COPY $TARGETPLATFORM/catacomb /usr/bin/catacomb

RUN adduser -D -u 65532 catacomb
USER catacomb

ENTRYPOINT ["/usr/bin/catacomb"]
CMD ["--help"]
