package codepolicy

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

var (
	allowedDirective = regexp.MustCompile(`^//go:(build|embed|generate)\b`)
	skipDirs         = map[string]bool{".git": true, "testdata": true, "vendor": true, "bin": true, "dist": true}
)

func violations(fset *token.FileSet, file *ast.File) []string {
	if ast.IsGenerated(file) {
		return nil
	}
	var found []string
	for _, group := range file.Comments {
		for _, comment := range group.List {
			if allowedDirective.MatchString(comment.Text) {
				continue
			}
			found = append(found, fmt.Sprintf("%d: %s", fset.Position(comment.Pos()).Line, firstLine(comment.Text)))
		}
	}
	return found
}

func scan(t *testing.T, src string) []string {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "sample.go", src, parser.ParseComments)
	require.NoError(t, err)
	return violations(fset, file)
}

func TestViolationsFlagsEveryNonDirectiveComment(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want []string
	}{
		{
			"line comment",
			"package p\n\nfunc f() {}\n\nvar x = 1 // trailing note\n",
			[]string{"5: // trailing note"},
		},
		{
			"doc comment",
			"package p\n\n// F does things.\nfunc F() {}\n",
			[]string{"3: // F does things."},
		},
		{
			"block comment reported by its first line only",
			"package p\n\n/* first\nsecond */\nfunc F() {}\n",
			[]string{"3: /* first"},
		},
		{
			"commented-out code",
			"package p\n\nfunc F() {\n\t// old := 1\n}\n",
			[]string{"4: // old := 1"},
		},
		{
			"nolint is not a free pass",
			"package p\n\nvar x = 1 //nolint:gochecknoglobals\n",
			[]string{"3: //nolint:gochecknoglobals"},
		},
		{
			"lookalike directive with a space after the slashes",
			"package p\n\n// go:generate stringer\nfunc F() {}\n",
			[]string{"3: // go:generate stringer"},
		},
		{
			"go directive outside the allowed three",
			"package p\n\n//go:linkname f runtime.f\nfunc F() {}\n",
			[]string{"3: //go:linkname f runtime.f"},
		},
		{
			"every comment in a file is reported",
			"package p\n\n// one\nfunc F() {} // two\n",
			[]string{"3: // one", "4: // two"},
		},
		{
			"go:generate is allowed",
			"package p\n\n//go:generate stringer -type=T\nfunc F() {}\n",
			nil,
		},
		{
			"go:embed is allowed",
			"package p\n\nimport _ \"embed\"\n\n//go:embed x.txt\nvar x string\n",
			nil,
		},
		{
			"go:build is allowed",
			"//go:build linux\n\npackage p\n",
			nil,
		},
		{
			"generated files are skipped wholesale",
			"// Code generated by stringer. DO NOT EDIT.\n\npackage p\n\n// a forbidden comment\nfunc F() {}\n",
			nil,
		},
		{
			"a clean file has no violations",
			"package p\n\nfunc F() {}\n",
			nil,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, scan(t, tt.src))
		})
	}
}

func TestNoCommentsInGoCode(t *testing.T) {
	root := moduleRoot(t)
	fset := token.NewFileSet()
	var scanned int

	walkErr := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if skipDirs[d.Name()] {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		file, parseErr := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if parseErr != nil {
			return parseErr
		}
		scanned++
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			rel = path
		}
		for _, v := range violations(fset, file) {
			t.Errorf("%s:%s: comments are forbidden; see AGENTS.md", rel, v)
		}
		return nil
	})
	if walkErr != nil {
		t.Fatalf("walk source tree: %v", walkErr)
	}
	require.Greater(t, scanned, 100, "the walk must actually reach the repository's Go files")
}

func firstLine(s string) string {
	before, _, _ := strings.Cut(s, "\n")
	return before
}

func moduleRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for {
		if _, statErr := os.Stat(filepath.Join(dir, "go.mod")); statErr == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("go.mod not found above working directory")
		}
		dir = parent
	}
}
